[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = "base" }
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = "base-sepolia" }

[fuzz]
runs = 1000

[invariant]
runs = 256
